### ISSUE TITLE
enable zipcode query

### ISSUE THREAD

**Issue by Zugabe** [meteomatics/python-connector-api#10]
I would like to use meteomatics.api.query_time_series() with zipcode instead of latlon_tuple_list

**Comment by meteomatics** [comment]
Hi @Zugabe ,

thanks for the input.

Would this function help you: https://github.com/meteomatics/python-connector-api/blob/548cea1fcb29ef224f7aa1ba6c0090cc693c88a4/meteomatics/api.py#L365 ? 

For the next major version, we are going to try to make it as one function.

Best regards

**Comment by Zugabe** [comment]
That's great, thanks for the fast reply.
