### ISSUE TITLE
from_items is deprecated in api.py

### ISSUE THREAD

**Issue by quackersian** [meteomatics/python-connector-api#14]
using a basic api query, I get the following warning:

"FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order."

This is comes from:
 C:\Users\MYUSERHERE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\meteomatics\api.py", line 195

The code still works, but I think the from_items needs to be replaced with from_dict instead

**Comment by meteomatics** [comment]
Cloased by #15
