### ISSUE TITLE
Pandas 1.0.0 breaks the current release 

### ISSUE THREAD

**Issue by nabobalis** [meteomatics/python-connector-api#17]
I saw that the changes were made in master to account for pandas but could we please get a release with these changes?

**Comment by make-ing** [comment]
+1

**Comment by meteomatics** [comment]
Realease 2.0.5 has just been pushed to PyPi

**Comment by nabobalis** [comment]
Thank you very much!

**Comment by make-ing** [comment]
Thank you guys for the fast response... long life Meteomatics 🍕🍻
