### ISSUE TITLE
api.query_time_series incompatible with Pandas 1.0

### ISSUE THREAD

**Issue by chrisjclarke** [meteomatics/python-connector-api#18]
Error produced is : 

"Failed, the exception is type object 'DataFrame' has no attribute 'from_items'"

stack trace points to source code line in api.py:

df = pd.DataFrame.from_items(dict_data.items(), orient="index", columns=lons)

This is because:

"pandas.DataFrame.from_items - Deprecated since version 0.23.0: from_items is deprecated and will be removed in a future version. Use DataFrame.from_dict(dict(items)) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order."

**Comment by maekke97** [comment]
Did you use the latest version of our connector? (See #15)
