### ISSUE TITLE
Package and provide setup.py

### ISSUE THREAD

**Issue by samwisehawkins** [meteomatics/python-connector-api#2]
It would be nice  (and easy) to package the API and provide a setup.py.

**Comment by meteomatics** [comment]
Hi!
That is indeed a good idea. We will do that!
Thanks for the input, and hopefully you are already a fan of our API!
Cheers, Christian

**Comment by make-ing** [comment]
+1

**Comment by samwisehawkins** [comment]
Yes, the API is great. Thanks.

**Comment by meteomatics** [comment]
Setup.py added in the version 2.0.0
