### ISSUE TITLE
query_lightnings fails on timezone issue

### ISSUE THREAD

**Issue by samwisehawkins** [meteomatics/python-connector-api#27]
meteomatics.api.query_lightnings(start, end, n,e,s,w,username,password)

    TypeError: Already tz-aware, use tz_convert to convert.

**Comment by meteomatics** [comment]
Thank you for raising the incident. As we were unable to observed the error locally we'll close this ticket.  
Could you please make sure that you use the latest version of the library, and supply a minimal example that reproduces the error in a New issue?
