### ISSUE TITLE
Attribute keys in requested netCDF contain ':' 

### ISSUE THREAD

**Issue by samwisehawkins** [meteomatics/python-connector-api#3]
This is a minor bug (or perhaps a feature). When you request a netdCDF file via the API, the attributekeys contain a ':', e.g. 

    ds = xarray.open_dataset(f)

    Attributes:
        Source::     MeteoCache
        Model::      ecmwf-ifs
        Parameter::  t_2m
        Service::    Meteomatics AG
        Website::    www.meteomatics.com
        Contact::    info@meteomatics.com

     ds.attrs['Model:']
     'ecmwf-ifs'

**Comment by meteomatics** [comment]
Hi

Thanks for the hint, the fix will be online with the next deploy within the next few days.

Christian
