### ISSUE TITLE
The most recent release has broken query_station_list when no parameters are provided

### ISSUE THREAD

**Issue by salimfadhleyhtp** [meteomatics/python-connector-api#34]
```
  File "C:\installs\anaconda\envs\eunrg_weather_control\lib\site-packages\meteomatics\api.py", line 96, in query_station_list
    url_params_dict = parse_query_station_params(source, parameters, startdate, enddate, location, elevation, id)
  File "C:\installs\anaconda\envs\eunrg_weather_control\lib\site-packages\meteomatics\parsing_util.py", line 260, in parse_query_station_params
    'parameters': ','.join((p for p in parameters)) if len(parameters) > 1 else parameters[0],
TypeError: object of type 'NoneType' has no len()
```

Background:
The most recent change to this package introduces changes to **parse_query_station_params** which fail if any of the following conditions are true:
* Start Date is null
* End Date is null
* Parameters are null or empty

I've prepared a PR which fixes this bug here:
https://github.com/meteomatics/python-connector-api/pull/33

**Comment by meteomatics** [comment]
Thank you very much for pointing out to that issue and of course thank you very much for already providing a solution for it!

We'll check the PR in detail and merge it afterwards.

**Comment by meteomatics** [comment]
the latest v2.2.1 release should fix this. If not, please reopen.
