### ISSUE TITLE
Error when extracting wind speed

### ISSUE THREAD

**Issue by TanguyLevent** [meteomatics/python-connector-api#35]
When I want to extract the wind speed with "wind_speed_10m" as parameter I've an issue: 'Parameter wind_speed_10m not available in model mix'.

**Comment by meteomatics** [comment]
Dear @TanguyLevent can supply a minimal example? Judging from the error message, I would say you need to supply a unit with the parameter, i.e. `'wind_speed_10m:ms'`, `'wind_speed_10m:kn'`, `'wind_speed_10m:kmh'` or `'wind_speed_10m:bft'` depending on what you are looking for exactly. The complete alphabetic list of available parameters can be look up at https://www.meteomatics.com/en/api/available-parameters/alphabetic-list/

Let me know if that helps.

Kind regards
Markus

**Comment by TanguyLevent** [comment]
thank you Markus, it is exactly what you mentionned. I forget the supply unit... 
Best, Tanguy
