### ISSUE TITLE
add feature to use a proxy server

### ISSUE THREAD

**Issue by make-ing** [meteomatics/python-connector-api#39]
Some companies may require the use of a proxy server to access external data sources. It would be nice to include such a feature directly into the meteomatics package. It should be very easy since the requests library used internaly allready supports this. For now the only method i see is to monkey patch the api.get_request and api.post_request functions. For anyone who needs some code examples, here is my current solution to the proxy problem:

```python
    old_get_request = api.get_request
    
    def get_request_wrapper(*args, **kwargs):
        return old_get_request(*args, **kwargs, proxies={"https": "http://0.0.0.0:8899"})

    api.get_request = get_request_wrapper
```

**Comment by make-ing** [comment]
@meteomatics: Are there any news on this topic from your side?

**Comment by bbuman** [comment]
Dear @make-ing 
I'm happy to inform you that this feature is now included in the most recent version of the api connector. 

Thank you for (re-)raising this issue.

**Comment by make-ing** [comment]
Cool... Thanks! I will not test this now but have high trust in you guys and so I will close this issue now.
