### ISSUE TITLE
no module named __version__ after install 

### ISSUE THREAD

**Issue by samwisehawkins** [meteomatics/python-connector-api#4]
I get problems after install:

    python setup.py install

Then when I do 
 
    import meteomatics.api

    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-1-0b936cc647c1> in <module>
    ----> 1 import meteomatics.api

    python-connector-api\meteomatics\__init__.py in <module>
    ----> 1 from __version__ import __version__

    ModuleNotFoundError: No module named '__version__'

It may be a python3 issue, where relative imports are handled differently.

**Comment by samwisehawkins** [comment]
I got similar issues with rounding and binary reader as well. I think you need to preceed the imports with a '.' to make it work with Python 3

**Comment by meteomatics** [comment]
Hi,

thanks for letting us know, we fixed it in the 2.0.1 version. 

Best regards,

Nino
