### ISSUE TITLE
How to find historical weather at a location at ONE time instead of a time series?

### ISSUE THREAD

**Issue by kevinlinxc** [meteomatics/python-connector-api#54]
Title, 

It seems like the api can do a single time but I just need an example of how to do it with the python client 
![image](https://user-images.githubusercontent.com/44324811/195652988-050cd239-c402-443a-a3a7-77bfca85577c.png)

**Comment by jesusmb1995** [comment]
You just have to specify one date-time for example: `https://api.meteomatics.com/2022-10-13T04:30:00Z/parameter/location/output`
