### ISSUE TITLE
Distinguish between different types of exception

### ISSUE THREAD

**Issue by Thomasillo** [meteomatics/python-connector-api#6]
Currently, the WeatherApiException is thrown for all sorts of errors

1. When user input is wrong (eg a parameter is requested that is not available, or the model is not covering the requested position)
2. When a connection error occurs (requests.ConnectionError is caught and a WeatherApi exception thrown not even using `raise from`)
3. When an API limit is reached.

It would be very desirable to distinguish these types also by the type of error possibly by subclassing the WeatherApiException.

One use case is automated requests to the weather API using a backoff handler (automated retry with time delay). In case 2 and 3 backing off is sensible, in case 1 it isn't. Currently it's only possible to distinguish by parsing the error message which is really bad style.

**Comment by meteomatics** [comment]
Hi @Thomasillo, thanks for the input.

Sure, it makes sense and it would be much easier to handle errors. We'll add it soon, most likely by the end of this week.

**Comment by meteomatics** [comment]
Hi @Thomasillo, different exceptions are now available in the version 2.0.4.

Thank you and best regards
